//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nominas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int ID_Asistencia { get; set; }
        public byte Horas_Cumplidas { get; set; }
        public byte Horas_Extras { get; set; }
        public int Codigo_Empleado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
