//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nominas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int Codigo_Comprobante { get; set; }
        public int Codigo_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
