//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nominas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nomina()
        {
            this.Retencions = new HashSet<Retencion>();
        }
    
        public int Codigo_Nomina { get; set; }
        public int Codigo_Empleado { get; set; }
        public decimal Sueldo { get; set; }
        public Nullable<decimal> Horas_Extras { get; set; }
        public Nullable<decimal> Bonificaciones { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retencion> Retencions { get; set; }
    }
}
